// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

#nullable disable

namespace E_Commerce.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251109155905_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Devices, gadgets, and accessories such as phones, laptops, and headphones.",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Clothing, shoes, and accessories for men, women, and kids.",
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Furniture, appliances, and kitchen tools for your home.",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fiction, non-fiction, and educational books across different genres.",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Equipment and apparel for fitness, sports, and outdoor activities.",
                            Name = "Sports & Outdoors"
                        });
                });

            modelBuilder.Entity("Entities.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Embedding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "6.5-inch OLED display, 128GB storage, 5G support.",
                            ImagePath = "/images/products/smartphone.jpg",
                            Name = "Smartphone X12",
                            Price = 899.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Noise-cancelling over-ear Bluetooth headphones.",
                            ImagePath = "/images/products/headphones.jpg",
                            Name = "Wireless Headphones",
                            Price = 199.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Intel i7, RTX 4060, 16GB RAM, 1TB SSD.",
                            ImagePath = "/images/products/gaming-laptop.jpg",
                            Name = "Gaming Laptop G15",
                            Price = 1499.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Heart rate monitor, GPS, and water-resistant design.",
                            ImagePath = "/images/products/smartwatch.jpg",
                            Name = "Smartwatch Pro",
                            Price = 249.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Classic fit, 100% cotton denim jacket.",
                            ImagePath = "/images/products/denim-jacket.jpg",
                            Name = "Men’s Denim Jacket",
                            Price = 79.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Lightweight running shoes with breathable mesh.",
                            ImagePath = "/images/products/sneakers.jpg",
                            Name = "Women’s Sneakers",
                            Price = 59.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Soft fleece hoodie, available in multiple colors.",
                            ImagePath = "/images/products/hoodie.jpg",
                            Name = "Unisex Hoodie",
                            Price = 49.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Genuine leather wallet with RFID protection.",
                            ImagePath = "/images/products/wallet.jpg",
                            Name = "Leather Wallet",
                            Price = 39.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Healthy cooking with little to no oil, 5L capacity.",
                            ImagePath = "/images/products/airfryer.jpg",
                            Name = "Air Fryer XL",
                            Price = 149.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "16-piece dinnerware set, microwave safe.",
                            ImagePath = "/images/products/dinner-set.jpg",
                            Name = "Ceramic Dinner Set",
                            Price = 89.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Bagless, high-suction vacuum cleaner.",
                            ImagePath = "/images/products/vacuum.jpg",
                            Name = "Vacuum Cleaner 3000",
                            Price = 179.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "1.7L stainless steel kettle with auto shut-off.",
                            ImagePath = "/images/products/kettle.jpg",
                            Name = "Electric Kettle",
                            Price = 39.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "A Handbook of Agile Software Craftsmanship by Robert C. Martin.",
                            ImagePath = "/images/products/clean-code.jpg",
                            Name = "Clean Code",
                            Price = 49.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Your Journey to Mastery by Andrew Hunt and David Thomas.",
                            ImagePath = "/images/products/pragmatic-programmer.jpg",
                            Name = "The Pragmatic Programmer",
                            Price = 44.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Elements of Reusable Object-Oriented Software.",
                            ImagePath = "/images/products/design-patterns.jpg",
                            Name = "Design Patterns",
                            Price = 54.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "An Easy & Proven Way to Build Good Habits and Break Bad Ones by James Clear.",
                            ImagePath = "/images/products/atomic-habits.jpg",
                            Name = "Atomic Habits",
                            Price = 29.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "21-speed bike with durable aluminum frame.",
                            ImagePath = "/images/products/mountain-bike.jpg",
                            Name = "Mountain Bike",
                            Price = 499.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Non-slip, eco-friendly yoga mat, 6mm thickness.",
                            ImagePath = "/images/products/yoga-mat.jpg",
                            Name = "Yoga Mat",
                            Price = 29.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "Professional size 5 football with durable grip.",
                            ImagePath = "/images/products/football.jpg",
                            Name = "Football",
                            Price = 19.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Description = "Lightweight graphite racket for advanced players.",
                            ImagePath = "/images/products/tennis-racket.jpg",
                            Name = "Tennis Racket",
                            Price = 89.99m,
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("Entities.Model.Product", b =>
                {
                    b.HasOne("Entities.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Model.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
